# Used by the release GitHub Actions workflow.
version: "3"
services:
  server:
    image: ghcr.io/ystv/badger/server:v1.0.4-rc.7
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment: &badger_env
      DATABASE_URL: "postgres://root:postgres@postgres:5432/badger_test?sslmode=disable"
      TUS_ENDPOINT: "http://tusd:1080/files"
      PUBLIC_TUS_ENDPOINT: "http://localhost:1080/files"
      S3_ENDPOINT: "http://minio:9000"
      AWS_ACCESS_KEY_ID: "root"
      AWS_SECRET_ACCESS_KEY: "rootroot"
      AWS_REGION: "us-east-1"
      STORAGE_BUCKET: "badger"
      API_SHARED_SECRET: "password"
      PUBLIC_URL: "http://localhost:3000"
      JWT_SIGNING_KEY: "somesecret"
      NODE_ENV: "test"
      E2E_TEST: "true"

  jobrunner:
    image: ghcr.io/ystv/badger/jobrunner:v1.0.4-rc.7
    platform: linux/amd64
    command: ["--watch", "--healthPort", "28342"] # matching server/playwright.config.ts
    ports:
      - "28342:28342"
    environment: *badger_env
