on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: "Branch, tag, or commit to build."
      tag:
        type: string
        required: true
        description: Version to build, also the docker tag
      strip_rc:
        type: boolean
        description: Strip -rc suffix from version number

permissions:
  contents: read
  packages: write

jobs:
  build-desktop-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        type: [public, ystv]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - run: yarn install --immutable

      - name: Set version
        shell: pwsh
        run: |
          $pkg = Get-Content ./desktop/package.json | ConvertFrom-Json
          $pkg.version = "${{inputs.tag }}" -replace "^v", ""
          if ("${{ inputs.strip_rc }}" -eq "true") {
            $pkg.version = $pkg.version -replace "-rc.*", ""
          }
          $pkg | ConvertTo-Json -Depth 32 | Set-Content ./desktop/package.json

      - run: "yarn package --win --publish never"
        working-directory: ./desktop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESKTOP_SENTRY_DSN: ${{ secrets.DESKTOP_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          ENVIRONMENT: prod
          IS_YSTV_BUILD: ${{ matrix.type == 'ystv' && 'true' || 'false' }}

      - name: Clean up
        run: Remove-Item -Recurse -Force ./desktop/dist/win-unpacked
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          path: ./desktop/dist
          name: badger-desktop-windows${{ matrix.type == 'ystv' && '-ystv' || '' }}

  build-docker-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version
        run: |
          set -x
          version=$(echo '${{ inputs.tag }}' | sed 's/^v//')
          if [[ '${{ inputs.strip_rc }}' == 'true' ]]; then
            version=$(echo $version | sed 's/-rc.*//')
          fi
          cat package.json | jq '.version = "'$version'"' | tee package.json
        working-directory: ./jobrunner
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ystv/badger/server
          flavor: latest=true
          tags: |
            type=raw,value=${{ inputs.tag }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.server
          secret-envs: SENTRY_AUTH_TOKEN=SENTRY_AUTH_TOKEN
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  build-docker-jobrunner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version
        run: |
          version=$(echo '${{ inputs.tag }}' | sed 's/^v//')
          if [[ '${{ inputs.strip_rc }}' == 'true' ]]; then
            version=$(echo $version | sed 's/-rc.*//')
          fi
          cat package.json | jq '.version = "'$version'"' | tee package.json
      - name: Docker metadata
        id: jr_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ystv/badger/jobrunner
          flavor: latest=true
          tags: |
            type=raw,value=${{ inputs.tag }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.jr_meta.outputs.tags }}
          labels: ${{ steps.jr_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.jobrunner
          secret-envs: SENTRY_AUTH_TOKEN=SENTRY_AUTH_TOKEN
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
