name: "Danger JS"
on: [pull_request]

jobs:
  danger:
    name: Danger JS
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/danger/danger-js:11.2.7
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        run: danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
