name: "Danger JS"
on: [pull_request]

jobs:
  danger:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: danger/danger-js@11.2.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
