name: "Danger JS"
on: [pull_request]

jobs:
  danger:
    name: Danger JS
    permissions:
      actions: write
      checks: write
      contents: read
      # deployments: read
      issues: write
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/danger/danger-js:12.3.3
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        run: danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
