name: Desktop Build (Windows)

on:
  workflow_dispatch: {}
  release:
    types: [prereleased, released]

jobs:
  build-desktop-windows:
    runs-on: windows-latest

    permissions:
      contents: write
      statuses: write
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable
      
      - name: Set DEV label for productName
        if: github.event.action != 'released'
        uses: jossef/action-set-json-field@v2.1
        with:
          file: ./desktop/package.json
          field: productName
          value: "Bowser Desktop (DEV)"

      - run: "yarn ${{ github.event_name == 'release' && 'publish' || 'make' }}"
        working-directory: ./desktop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: ls desktop/out/make

      - uses: actions/upload-artifact@v3
        with:
          name: desktop
          path: ./desktop/out/make
        if: github.event_name != 'release' # because 'publish' will take care of it
