name: Desktop Build (Windows)

on:
  push:
    branches: [main]

jobs:
  build-desktop-windows:
    runs-on: windows-latest

    permissions:
      contents: write
      statuses: write
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable
      
      - run: yarn publish
        working-directory: ./desktop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
