name: Desktop Build (Windows)

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: "Branch, tag, or commit to build."
        required: true
      do_release:
        type: boolean
        description: "Whether to upload the release to GitHub."
        default: false
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      prerelease:
        type: boolean
        default: false
      do_release:
        type: boolean
        description: "Whether to upload the release to GitHub."
        default: true

jobs:
  build-desktop-windows:
    runs-on: windows-latest

    permissions:
      contents: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - run: yarn install --immutable

        # This is negated because a workflow_call won't have the do_release input, and we want to publish then.
      - run: "yarn package ${{ inputs.do_release && '--publish onTagOrDraft' || '' }}"
        working-directory: ./desktop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESKTOP_SENTRY_DSN: ${{ secrets.DESKTOP_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          ENVIRONMENT: ${{ inputs.prerelease && 'dev' || 'prod' }}

      - run: ls desktop/out/make

      - uses: actions/upload-artifact@v3
        with:
          name: desktop
          path: ./desktop/out/make
        # prettier-ignore
        if: '! inputs.do_release' # because 'publish' will take care of it
