name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prettier:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable --inline-builds

      - run: yarn prettier --check '{desktop,jobrunner,server}/**/*.{ts,tsx}'

  lint-desktop:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable --inline-builds

      - run: yarn lint
        working-directory: ./desktop

  lint-server:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable --inline-builds

      - run: yarn lint
        working-directory: ./server

  # TODO: jobrunner lint

  typecheck-desktop:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable --inline-builds

      - run: yarn typecheck
        working-directory: ./desktop

  typecheck-server:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable --inline-builds

      - run: yarn typecheck
        working-directory: ./server

  typecheck-jobrunner:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable --inline-builds

      - run: yarn typecheck
        working-directory: ./jobrunner

  test-unit-desktop:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable --inline-builds

      - run: yarn test --coverage
        working-directory: ./desktop

  test-unit-server:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: yarn install --immutable --inline-builds

      - run: yarn test --coverage
        working-directory: ./server

  test-integration-server-jobrunner:

    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgres://root:postgres@localhost:5432/bowser_test

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - run: docker compose up -d

      - run: yarn install --immutable --inline-builds

      - run: yarn prisma migrate deploy
        working-directory: ./utility/prisma

      - run: yarn test:integration

  test-e2e-server:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      E2E_TEST: 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Start services
        run: docker compose up -d

      - name: Install dependencies
        run: yarn install --immutable --inline-builds

      - name: Build server
        run: |
          yarn build
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static
        working-directory: ./server

      # Adapted from https://playwrightsolutions.com/playwright-github-action-to-cache-the-browser-binaries/
      - name: Get installed Playwright version
        id: playwright-version
        run: yarn info --json @playwright/test >> $GITHUB_OUTPUT
        working-directory: ./server

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ fromJson(steps.playwright-version.outputs.stdout).children[0].Version }}

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ./server
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: ./server

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

